import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.231.7:8080/ccs-web/login/auth');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('italo');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Juni@r041');
  await page.getByRole('button', { name: ' Login' }).click();
  await page.getByRole('link', { name: 'English' }).click();
  await page.getByRole('link', { name: '+  Add' }).click();
  await page.getByText('Debit Account Product / Pre-').click();
  await page.getByRole('button', { name: 'Next' }).click();

  await page.getByLabel('Account Category', { exact: true }).selectOption('Saving - 02');
  await page.getByLabel('Base Currency').selectOption('840');
  await page.getByLabel('Default Holder Classification').selectOption('1');
  await page.getByRole('textbox', { name: 'Account Product Number *' }).click();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).fill('1000872');
  await page.getByRole('textbox', { name: 'Account Product Name *' }).click();
  await page.getByRole('textbox', { name: 'Account Product Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Account Product Name *' }).fill('DEBIT AUTO');
  await page.getByLabel('Status').selectOption('1');
  await page.getByRole('textbox', { name: 'Start Date *' }).click();
  await page.getByRole('cell', { name: '«' }).click();
  await page.getByRole('cell', { name: 'February' }).click();
  await page.getByRole('cell', { name: '2026' }).click();
  await page.getByText('2025', { exact: true }).click();
  await page.getByText('Nov').click();
  await page.getByRole('cell', { name: '19' }).click();
  await page.getByRole('textbox', { name: 'End Date *' }).click();
  await page.getByRole('cell', { name: 'March' }).click();
  await page.getByRole('cell', { name: 'March' }).click();
  await page.getByText('Auto-Generate Account Number').click();
  await page.getByRole('textbox', { name: 'Account Number Total Length *' }).click();
  await page.getByRole('textbox', { name: 'Account Number Total Length *' }).fill('7');
  await page.getByRole('textbox', { name: 'IAI Length' }).click();
  await page.getByRole('textbox', { name: 'IAI Length' }).fill('3');
  await page.getByLabel('Check Digit Type').selectOption('0');
  await page.getByLabel('Branch Number').selectOption('0001');
  await page.getByRole('button', { name: 'Save & Continue ' }).click();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).dblclick();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).fill('481');
  await page.getByRole('button', { name: 'Save & Continue ' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).click();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).dblclick();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).fill('9');
  await page.getByRole('textbox', { name: 'Account Product Number *' }).click();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).fill('487');
  await page.getByRole('button', { name: 'Save & Continue ' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('textbox', { name: 'Account Number Total Length *' }).click();
  await page.getByRole('textbox', { name: 'Account Number Total Length *' }).fill('12');
  await page.getByRole('textbox', { name: 'Account Product Number *' }).dblclick();
  await page.getByRole('textbox', { name: 'Account Product Number *' }).fill('091');
  
  await page.getByRole('button', { name: 'Save & Continue ' }).click();
  await page.getByLabel('Prepaid Operating Mode').selectOption('0');
  await page.getByRole('button', { name: 'Save & Continue ' }).click();
  await page.getByRole('searchbox', { name: 'Search Menu' }).click();
  await page.getByRole('searchbox', { name: 'Search Menu' }).fill('ACCOUN');
  await page.getByRole('link', { name: ' Account Products' }).click();
  await page.getByRole('searchbox', { name: 'Search:' }).click();
  await page.getByRole('searchbox', { name: 'Search:' }).fill('091');
  await page.getByRole('gridcell', { name: 'DEBIT AUTO' }).click();
  await page.getByRole('gridcell', { name: '091' }).click();
  await page.getByRole('gridcell', { name: 'Saving', exact: true }).click();
  await page.getByRole('gridcell', { name: 'DEBIT AUTO' }).click();
});